description: gaminax/texts
theme: minima
github_username: gaminax
github: [metadata]
exclude: [docs]
url: texts

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-asciidoc

asciidoc:
    ext: ad, adoc, asciidoc

